sudo: required

language: node_js
node_js:
  - "v10.16.2"

services:
  - docker

before_install:
  - mkdir -p manager2/dist
  - docker build -t osallou/my .
  - npm install

script:
  - npm install -g mocha
  - cd $TRAVIS_BUILD_DIR/tests && docker-compose up -d
  - cd $TRAVIS_BUILD_DIR && sleep 180 && docker ps &&  docker logs tests_my-app_1 && mocha -t 10000
  - cd $TRAVIS_BUILD_DIR/tests && docker-compose down
